# Generated by Django 3.0 on 2021-08-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_num',
            field=models.PositiveIntegerField(default=0, verbose_name='选项数目'),
        ),
    ]
