# Generated by Django 3.0 on 2021-08-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0002_question_option_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='user_id',
        ),
        migrations.AddField(
            model_name='submit',
            name='username',
            field=models.CharField(blank=True, max_length=128, verbose_name='用户名'),
        ),
    ]
