# Generated by Django 3.0 on 2021-08-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0003_auto_20210821_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='release_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
    ]
