# Generated by Django 3.0 on 2021-08-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0004_auto_20210821_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='username',
            field=models.CharField(max_length=128, verbose_name='用户名'),
        ),
    ]
