# Generated by Django 3.0 on 2021-08-21 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=256, verbose_name='副标题')),
                ('question_num', models.PositiveIntegerField(default=0, verbose_name='题目数目')),
                ('recycling_num', models.PositiveIntegerField(default=0, verbose_name='回收数目')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('release_time', models.DateTimeField(blank=True, verbose_name='发布时间')),
                ('finished_time', models.DateTimeField(blank=True, verbose_name='结束时间')),
                ('is_released', models.BooleanField(default=False, verbose_name='是否已发行')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('is_collected', models.BooleanField(default=False, verbose_name='是否已收藏')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('type', models.IntegerField(choices=[(0, '普通问卷'), (1, '考试问卷'), (2, '投票问卷'), (3, '报名问卷')], default=0, verbose_name='问卷类型')),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='提交编号')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qn.Survey', verbose_name='问卷编号')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.User', verbose_name='用户编号')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='问题id')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('direction', models.CharField(blank=True, max_length=256, verbose_name='说明')),
                ('is_must_answer', models.BooleanField(default=False, verbose_name='是必答题')),
                ('sequence', models.IntegerField(default=0, verbose_name='题目顺序')),
                ('type', models.IntegerField(choices=[(0, '单选'), (1, '多选'), (2, '填空'), (3, '评分')], default=0, verbose_name='题型')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qn.Survey', verbose_name='所属问卷id')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='选项编号')),
                ('content', models.CharField(max_length=128, verbose_name='内容')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qn.Question', verbose_name='问题编号')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='回答编号')),
                ('answer', models.CharField(max_length=128, verbose_name='答案')),
                ('type', models.IntegerField(choices=[(0, '单选'), (1, '多选'), (2, '填空'), (3, '评分')], default=0, verbose_name='题目类型')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qn.Question', verbose_name='问题编号')),
                ('submit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qn.Submit', verbose_name='提交编号')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.User', verbose_name='用户编号')),
            ],
        ),
    ]
