# Generated by Django 3.0 on 2021-08-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.CharField(default='', max_length=256, verbose_name='正确答案'),
        ),
    ]
