# Generated by Django 3.0 on 2021-08-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0002_auto_20210821_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='share_url',
            field=models.URLField(default='', verbose_name='分享链接'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.CharField(default='', max_length=32, verbose_name='问题类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, default='默认标题', max_length=64, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(default='radio', max_length=256, verbose_name='问题类型'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='type',
            field=models.CharField(default='', max_length=32, verbose_name='问卷类型'),
        ),
    ]
