# Generated by Django 3.0 on 2021-08-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0003_remove_survey_begin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.PositiveIntegerField(default=0, verbose_name='问题得分'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='打分最高分'),
        ),
    ]
