# Generated by Django 3.0 on 2021-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0004_auto_20210826_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='num_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='最大额度'),
        ),
        migrations.AddField(
            model_name='option',
            name='remain_num',
            field=models.PositiveIntegerField(default=0, verbose_name='剩余额度'),
        ),
    ]
