# Generated by Django 3.0 on 2021-08-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0004_auto_20210826_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='max_recycling',
            field=models.PositiveIntegerField(default=999999, verbose_name='最大回收数目'),
        ),
    ]
