# Generated by Django 3.0 on 2021-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0005_auto_20210826_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='has_num_limit',
            field=models.BooleanField(default=False, verbose_name='是否有额度限制'),
        ),
    ]
