# Generated by Django 3.0 on 2021-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0005_auto_20210822_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
