# Generated by Django 3.0 on 2021-08-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0006_option_has_num_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_image',
            field=models.BooleanField(default=False, verbose_name='包含图片'),
        ),
        migrations.AddField(
            model_name='question',
            name='has_video',
            field=models.BooleanField(default=False, verbose_name='包含视频'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(default='', verbose_name='图片链接'),
        ),
        migrations.AddField(
            model_name='question',
            name='isVote',
            field=models.BooleanField(default=False, verbose_name='是投票题'),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.URLField(default='', verbose_name='视频链接'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='max_recycling',
            field=models.PositiveIntegerField(default=999999, verbose_name='最大回收数目'),
        ),
    ]
