# Generated by Django 3.0 on 2021-08-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0007_auto_20210826_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='展示题目'),
        ),
        migrations.AddField(
            model_name='question',
            name='last_option',
            field=models.IntegerField(default=0, verbose_name='上一个选项'),
        ),
        migrations.AddField(
            model_name='question',
            name='last_question',
            field=models.IntegerField(default=0, verbose_name='上一个问题'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_logic',
            field=models.BooleanField(default=False, verbose_name='是否存在逻辑问题'),
        ),
    ]
