# Generated by Django 3.0 on 2021-08-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0007_submit_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='单题得分'),
        ),
        migrations.AddField(
            model_name='question',
            name='right_answer',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='正确答案'),
        ),
        migrations.AddField(
            model_name='submit',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='答卷总得分'),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_recycling',
            field=models.PositiveIntegerField(default=100, verbose_name='最大回收数目'),
        ),
    ]
