# Generated by Django 3.0 on 2021-08-27 20:17

import Qn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0008_auto_20210827_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='video_url',
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, upload_to=Qn.models.question_video_directory_path, verbose_name='视频文件'),
        ),
    ]
