# Generated by Django 3.0 on 2021-08-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0008_auto_20210823_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='excel_url',
            field=models.URLField(default='', verbose_name='答卷数据统计excel链接'),
        ),
    ]
