# Generated by Django 3.0 on 2021-08-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0009_auto_20210827_2017'),
        ('Qn', '0008_auto_20210827_1638'),
    ]

    operations = [
    ]
