# Generated by Django 3.0 on 2021-08-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qn', '0010_merge_20210828_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='video',
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='图片链接'),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='视频链接'),
        ),
    ]
