# Generated by Django 3.0 on 2021-08-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='id',
            new_name='answer_id',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='id',
            new_name='option_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='submit',
            old_name='id',
            new_name='submit_id',
        ),
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='选项位置'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_collected',
            field=models.BooleanField(default=False, verbose_name='是否被收藏'),
        ),
    ]
